{{- if .Values.strimzi.enabled -}}
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: {{ template "hindsight.fullname" . }}
spec:
  kafka:
    replicas: {{ .Values.strimzi.kafka.replicaCount }}
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      {{ if .Values.strimzi.kafka.storage.enabled }}
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      deleteClaim: false
      {{ else }}
      type: ephemeral
      {{ end }}
    {{ if .Values.strimzi.kafka.storage.enabled }}
    resources:
      requests:
        cpu: 500m
        memory: 1000M
      limits:
        cpu: 500m
        memory: 1000M
    {{ end }}
  zookeeper:
    replicas: {{ .Values.strimzi.kafka.replicaCount }}
    storage:
      {{ if .Values.strimzi.kafka.storage.enabled }}
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
        limits:
          cpu: 100m
          memory: 512Mi
      {{ else }}
      type: ephemeral
      {{ end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end -}}
