apiVersion: v2
name: hindsight
description: A data ingestion engine
type: application
version: 0.1.0
appVersion: 0.0.2
home: https://github.com/inhindsight
sources:
  - https://github.com/inhindsight/hindsight
