receive:
  service:
    type: ClusterIP
  service_tcp:
    type: LoadBalancer
broadcast:
  service:
    type: LoadBalancer
acquire:
  service:
    type: LoadBalancer
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi
strimzi:
  kafka:
    resources:
      requests:
        cpu: 500m
        memory: 8Gi
      limits:
        cpu: 1000m
        memory: 8Gi
  zookeeper:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 250m
        memory: 512Mi
redis:
  enabled: false
  externalAddress: ""
presto:
  postgres:
    enable: false
    service:
      externalAddress: ""
    db:
      user: ""
      password: ""
global:
  objectStore:
    region: "us-east-2"
    accessKey: ""
    accessSecret: ""
    minio:
      enabled: false
